site_name: htgithub94
site_url: https://htgithub194.github.io/
theme:
  name: material
  palette:
    - scheme: slate
      primary: indigo
      accent: indigo

plugins:
  - search
  - tags

extra:
  tags:
    index_page: tags.md 

nav:
  - Home: index.md

  - Brieft introduction to Rust: rust/introduce/introduce.html

  - Rust basic:
    - Brieft introduction to Rust: rust/introduce/introduce.html
    - Async Await are just the key words for Concurrency: rust/async/async.md
    - Memory layout of some data types: rust/memory_layout/memory_layout.md
    - Trait bound and ways for dispatching: rust/trai_bound_and_dispatching/trai_bound_and_dispatching.md
    - How Closure is implemented: rust/closure/closure.md
    - Enum is not just an integer: rust/enums/enums.md
    - Send & Sync trait: rust/send_sync/send_sync.md
    - Derive Clone: rust/clone/derive_clone.md

  - Rust Axum:
    - Axum is so power full !: rust/axum/axum.md
    - FromRef to extract sub-state: rust/axum/FromRef.md

  - Linux kernel:
    - Crash recovery and debugging: kernel/crash_recovery/crash_recovery.md
    - Watchdog module: kernel/watchdog/watchdog.md
    - Preempt: kernel/preempt/preempt.md
    - Minirootfs Alpine & internet connection: kernel/mini_alpine/mini_alpine.md

  - Networking:
    - Tunnel interface: networking/tunnel/tunnel.md
    - QEMU Cluster: networking/qemu_network/qemu.md

  - Others:
      - Conditional Variable & Rust channel: programming_concept/conditional_variable/conditional_variable.md
      - Dependency Injection: programming_concept/dependency_injection/dependency_injection.md

extra_css:
  - styles/horizontal_nav_bar.css
  - styles/tags.css

markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - admonition
    - pymdownx.arithmatex:
        generic: true
    - footnotes
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.mark
    - attr_list